version: '3'
services:
  gnpsurl-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnpsurl-dash
    volumes:
      - ./output:/app/output:rw
      - ./logs:/app/logs:rw
    ports:
    - "6558:5000"
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: urlformatter.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: urlformatter.gnps2.org
      LETSENCRYPT_EMAIL: miw023@ucsd.edu
    restart: on-failure
    command: /app/run_server.sh
    deploy:
      resources:
        limits:
          memory: 2000M


networks:
  nginx-net:
    external:
      name: nginx-net